import { type MyPage } from "@/components/layouts/types";
import { Check, Fingerprint, Globe2, Rocket } from "lucide-react";
import { useTheme } from "next-themes";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home: MyPage = () => {
  const { resolvedTheme } = useTheme();

  return (
    <>
      <Head>
        <title>TODO:APP - Case</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section
        className={`h-full w-full bg-gradient-to-b ${
          resolvedTheme === "dark"
            ? "from-slate-900 to-[#390561]"
            : "from-[#fff] to-[#d2a6f4]"
        } py-12 md:py-16 lg:py-20 xl:py-28`}
      >
        <div className="container px-4 md:px-6">
          <div className="grid items-center gap-6">
            <div className="flex flex-col justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h1
                  className={`bg-gradient-to-r ${
                    resolvedTheme === "dark"
                      ? "from-purple-600 to-indigo-300"
                      : "from-purple-700 to-indigo-300"
                  } bg-clip-text text-5xl font-extrabold tracking-tighter text-transparent drop-shadow-sm sm:text-7xl xl:text-8xl/none`}
                >
                  Modern Todo App
                </h1>
                <p
                  className={`mx-auto max-w-[600px] font-medium drop-shadow-xl ${
                    resolvedTheme === "dark" ? "text-zinc-200" : "text-gray-900"
                  } dark:text-zinc-100 md:text-xl`}
                >
                  Hızlı, güvenilir ve modern yaşamın ihtiyaçlarına göre
                  tasarlanmıştır.
                </p>
              </div>
            </div>
          </div>
        </div>
        <section className="text-gray-600">
          <div className="container mx-auto flex flex-col items-center md:flex-row md:px-24 md:py-10">
            <div className="md:w-1.5/2 mb-16 mt-5 flex flex-col items-center text-center md:mb-0 md:mt-0 md:items-start md:pr-16 md:text-left lg:flex-grow lg:pr-24">
              <h1 className="mb-3 text-2xl font-extrabold leading-9 tracking-tight text-gray-900 dark:text-gray-100 sm:text-4xl sm:leading-10 md:text-5xl md:leading-normal">
                Özellikler
              </h1>
              <div className="text-gray-900 dark:text-white">
                <div className="mb-4 text-center md:text-right">
                  <Check className="inline" />
                  <span className="ml-14">Kolay</span>
                </div>
                <div className="mb-4 text-center md:text-right">
                  <Globe2 className="inline" />
                  <span className="ml-10">Modern</span>
                </div>
                <div className="mb-4 text-center md:text-right">
                  <Rocket className="inline" />
                  <span className="ml-16">Hızlı</span>
                </div>
                <div className="mb-4 text-center md:text-right">
                  <Fingerprint className="inline" />
                  <span className="ml-8">Güvenilir</span>
                </div>
              </div>
              <div className="flex justify-center">
                <Link
                  href="/home"
                  className="inline-flex rounded border-0 bg-purple-600 px-6 py-2 text-lg text-white hover:bg-purple-500 focus:outline-none"
                >
                  Kullanmaya Başla
                </Link>
              </div>
            </div>
            <div className="mb-5 w-4/6 md:mb-0 md:w-1/2 lg:w-full lg:max-w-lg">
              <Image
                src="/landing-img.png"
                className="rounded object-cover object-center drop-shadow-xl"
                alt="Landing Page Image"
                width={720}
                height={600}
              />
            </div>
          </div>
        </section>
      </section>
    </>
  );
};

export default Home;
Home.Layout = "LandingPage";
